services:
  web:
    container_name: api_gateway
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - gateway_to_course_service
      - gateway_to_user_service
      - gateway_to_progress_service

networks:
  gateway_to_course_service:
    name: gateway_to_course_service_network
    driver: bridge

  gateway_to_user_service:
    name: gateway_to_user_service_network
    driver: bridge

  gateway_to_progress_service:
    name: gateway_to_progress_service_network
    driver: bridge
